# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 284ddc3de509e343c2b31ac61eb5c59cc7486e1371ba2bfdef9d65488e69af032155540f0300ace05a6ac84f1eacddd87c5312985a6da033714febdfe8d6cd11

test:
  secret_key_base: bf1e8c4704a7e91dd0e184e56720b3b54b5af66aa86788e20b2d54da75df32ee078cc63c2c4b7bebdab0c740777df694e4b6a66835f503d2142b5c515fc74736

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
